[build]
  # Publish the static_site folder, ignoring the root React app
  publish = "static_site"
  # No build command required for Vanilla JS
  command = "echo 'Deploying Static Engine v2.0'"

[context.production]
  publish = "static_site"

[context.deploy-preview]
  publish = "static_site"
