[build]
  base = "Downloads/iyara-side-restaurant"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/static_site/*"
  to = "/static_site/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
